# Base Image
FROM python:3.10-alpine

# Install packages required to build and use python libraries
RUN apk --update --no-cache add \
    curl \
    make \
    gcc \
    libressl-dev \
    musl-dev \
    libffi-dev

#Poetry https://python-poetry.org/docs/configuration/#using-environment-variables
ENV POETRY_VERSION=1.1.13

# Install poetry (nb: installs to /root/.local/bin, so we need to add that to the path)
RUN curl -sSL https://install.python-poetry.org | python -
ENV PATH $PATH:/root/.local/bin
