version: "3.9"
services:
  flask:
    build:
      context: .
      secrets:
        - topsecretkey
    ports:
      - "8080:5000"
    depends_on:
      - "redis"
    environment:
      FLASK_ENV: development
      REDIS_HOST: redis
  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"

secrets:
  topsecretkey:
    file: ./supersecret.txt
